### ISSUE TITLE
NoMethodError: undefined method `stub_const' for MyModule:Module

### ISSUE THREAD

**Issue by MatheusRich** [adammck/minitest-stub-const#13]
I've added you gem to my Gemfile and executed `bundle install`. But when I tried to mock a constant on a module called `MyModule` i just got this error:
`NoMethodError: undefined method 'stub_const' for MyModule:Module`

**Comment by MatheusRich** [comment]
My solution was add this line on my `test_helper.rb`
`require "minitest/stub_const"`

As I didn't find anything related to this step on README.md, I've opened a PR. Here it is #14

**Comment by adammck** [comment]
Merged the PR, thanks!
