### ISSUE TITLE
Can't stub ENV

### ISSUE THREAD

**Issue by garethrees** [adammck/minitest-stub-const#2]
Doesn't seem like you can stub ENV.

Here's my use case:

```ruby
env = ENV.to_hash.merge('HOME' => '/home/ruby')
stub_const(:ENV, env) do
  ENV['HOME'].must_equal '/home/ruby'
end
```

**Comment by adammck** [comment]
The documentation isn't very helpful about this, but you can stub globals like `ENV` by calling `stub_const` on `Object`. The following seems to work for me:

```
adammck@imac5k [git master 1d24576] [rbenv 2.1.5] 
~/code/src/github.com$ gem install minitest-stub-const
Fetching: minitest-stub-const-0.2.gem (100%)
Successfully installed minitest-stub-const-0.2
1 gem installed

adammck@imac5k [git master 1d24576] [rbenv 2.1.5]
~/code/src/github.com$ irb
irb(main):001:0> require "minitest/stub_const"
=> true
irb(main):002:0> env = ENV.to_hash.merge("HOME" => "/home/ruby"); nil
=> nil
irb(main):003:0> Object.stub_const(:ENV, env) { puts ENV["HOME"] }
/home/ruby
=> nil
irb(main):004:0> ENV["HOME"]
=> "/Users/adammck"
```

Does this work for you?

**Comment by garethrees** [comment]
Thanks for looking in to this :beers: 

I've tried your example in irb, and it works the same.

My test [fails](https://github.com/ddollar/github-backup/pull/15) though:

```ruby
it 'sets the default .gitconfig file path' do
  env = ENV.to_hash.merge("HOME" => "/home/ruby")
  Object.stub_const(:ENV, env) do
    config = GithubBackup::Config.new(:backup_root => '/tmp')
    config.gitconfig_path.must_equal '/home/ruby/.gitconfig'
  end
end
```
```
  1) Failure:
GithubBackup::Config::new#test_0003_sets the default .gitconfig file path [/Users/gareth/Code/ddollar/github-backup/spec/lib/github-backup/config_spec.rb:23]:
Expected: "/home/ruby/.gitconfig"
  Actual: "/Users/gareth/.gitconfig"
```

This passes:

```ruby
it 'stubs ENV' do
  env = ENV.to_hash.merge("HOME" => "/home/ruby")
  Object.stub_const(:ENV, env) do
    ENV['HOME'].must_equal '/home/ruby'
  end
end
```

**Comment by adammck** [comment]
On [config.rb:5](https://github.com/ddollar/github-backup/blob/master/lib/github-backup/config.rb#L5), you're storing the value of `ENV['HOME']` in a const, which is used later in `initialize`. So changing the value of `ENV['HOME']` will have no effect. You'll need to either change your test to use the constant, or change the object to read `ENV` later.

**Comment by garethrees** [comment]
Thanks for looking in to that. Just went with something [simpler](https://github.com/ddollar/github-backup/commit/09d85a7da5fa1a1e954d59d183f2131484864177).
