### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by balasankarc** [adammck/minitest-stub-const#4]
How to run tests of this gem? I tried `bundle exec rake` and got this output

/var/lib/gems/2.1.0/gems/bundler-1.8.3/lib/bundler/rubygems_integration.rb:261:in `block in replace_gem': rake is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
	from /usr/local/bin/rake:22:in `<main>'

**Comment by adammck** [comment]
There's a shell script in [`script/test`](https://github.com/adammck/minitest-stub-const/blob/master/script/test) which you can invoke to run the tests. I used [turn](https://rubygems.org/gems/turn) rather than rake for this gem, for reasons that I don't entirely recall.
